[package]
name = "telemetry-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
crossterm = "0.29.0"
ratatui = "0.29.0"
tokio = { version = "1.45.0", features = ["full"] }
